version: '1.0'
services:
  my_sql:
    container_name: my_sql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/init_db:/docker-entrypoint-initdb.d/:ro
      - ./database/mysql_data/:/var/lib/mysql