FROM python:3.10-slim-buster

WORKDIR /api

COPY ./ /api

RUN pip install fastapi uvicorn beautifulsoup4 apscheduler requests pytz

CMD ["bash", "-c", "uvicorn crawlApi:app --host 0.0.0.0 --port 1818 --reload"]